language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk8
  - openjdk7
install: mvn install -DskipTests=true -Dgpg.skip=true
after_success:
  - mvn clean test jacoco:report coveralls:report
sudo: false

